cmake_minimum_required(VERSION 3.21)

get_filename_component(ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
file(READ "${ROOT_DIR}/CMakePresets.json" presets)
execute_process(
    COMMAND ${CMAKE_COMMAND} --list-presets
    WORKING_DIRECTORY ${ROOT_DIR}
    OUTPUT_VARIABLE enabled
    ERROR_QUIET
)
string(REGEX MATCHALL "\"[^\"]+\"" enabled "${enabled}")
list(TRANSFORM enabled REPLACE "\"" "")

string(JSON count LENGTH "${presets}" configurePresets)
math(EXPR last "${count} - 1")
foreach(i RANGE ${last})
    string(JSON name GET "${presets}" configurePresets ${i} name)
    set(index_${name} ${i})
endforeach()

function(lookup name out)
    string(JSON value ERROR_VARIABLE missing GET "${presets}" configurePresets ${index_${name}} ${ARGN})
    if(missing)
        set(value "")
        string(JSON parents ERROR_VARIABLE orphan GET "${presets}" configurePresets ${index_${name}} inherits)
        if(NOT orphan)
            string(REGEX MATCHALL "[A-Za-z0-9_.-]+" parents "${parents}")
            foreach(parent IN LISTS parents)
                lookup(${parent} value ${ARGN})
                if(NOT value STREQUAL "")
                    break()
                endif()
            endforeach()
        endif()
    endif()
    set(${out} "${value}" PARENT_SCOPE)
endfunction()

set(total 0)
set(width 0)
set(available "")
set(unavailable "")
foreach(i RANGE ${last})
    string(JSON name GET "${presets}" configurePresets ${i} name)
    string(JSON hidden ERROR_VARIABLE ignored GET "${presets}" configurePresets ${i} hidden)
    if(hidden)
        continue()
    endif()
    math(EXPR total "${total} + 1")
    string(LENGTH "${name}" length)
    if(length GREATER width)
        set(width ${length})
    endif()
    set(reason "")
    if(NOT name IN_LIST enabled)
        lookup(${name} lhs condition lhs)
        lookup(${name} rhs condition rhs)
        if(lhs STREQUAL "\${hostSystemName}")
            set(reason "needs a ${rhs} host")
        else()
            set(reason "disabled on this host")
        endif()
    else()
        lookup(${name} generator generator)
        lookup(${name} compiler cacheVariables CMAKE_C_COMPILER)
        lookup(${name} linker cacheVariables CMAKE_EXE_LINKER_FLAGS)
        lookup(${name} sysroot cacheVariables CMAKE_SYSROOT)
        set(tools ${compiler})
        if(generator MATCHES "^Ninja")
            list(PREPEND tools ninja)
        endif()
        if(linker MATCHES "-fuse-ld=([a-z]+)")
            list(APPEND tools ld.${CMAKE_MATCH_1})
        endif()
        foreach(tool IN LISTS tools)
            find_program(path_${tool} ${tool} NO_CACHE)
            if(NOT path_${tool})
                set(reason "${tool} not found")
                break()
            endif()
        endforeach()
        if(reason STREQUAL "" AND sysroot AND NOT IS_DIRECTORY "${sysroot}")
            set(reason "${sysroot} not found")
        endif()
    endif()
    if(reason STREQUAL "")
        list(APPEND available "${name}")
    else()
        list(APPEND unavailable "${name}|${reason}")
    endif()
endforeach()

list(LENGTH available available_count)
list(LENGTH unavailable unavailable_count)
set(text "Available targets (${available_count} of ${total}):")
foreach(name IN LISTS available)
    string(APPEND text "\n  ${name}")
endforeach()
string(APPEND text "\n\nUnavailable targets (${unavailable_count} of ${total}):")
foreach(entry IN LISTS unavailable)
    string(REGEX REPLACE "\\|.*" "" name "${entry}")
    string(REGEX REPLACE "^[^|]*\\|" "" reason "${entry}")
    string(LENGTH "${name}" length)
    math(EXPR gap "${width} - ${length} + 2")
    string(REPEAT " " ${gap} pad)
    string(APPEND text "\n  ${name}${pad}${reason}")
endforeach()
execute_process(COMMAND ${CMAKE_COMMAND} -E echo "${text}")